# Generated by Django 5.0.7 on 2024-09-09 20:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
