version: '3.8'

services:
  web:
    build: .
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./secrets:/app/secrets  # Mount the secrets directory
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/django-service-account.json
      
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

# Commented out since we're using an external DB
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: portfoliodb
      POSTGRES_USER: andrauritu
      POSTGRES_PASSWORD: numauita
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
