version: '3.8'

services:
  web:
    build: .
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - /cloudsql:/cloudsql  # Mount the Cloud SQL socket
      - ./uploads:/app/uploads
      - ./secrets:/app/secrets  # Mount the secrets directory
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/django-service-account.json
      
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: portfoliodb
      POSTGRES_USER: andrauritu
      POSTGRES_PASSWORD: numauita
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
