# Generated by Django 5.0.7 on 2024-09-09 20:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorteducation', ckeditor.fields.RichTextField()),
                ('shortexperience', ckeditor.fields.RichTextField()),
                ('shortpersonal', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
