# Generated by Django 5.0.7 on 2024-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationsection',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
