# Generated by Django 5.0.7 on 2024-09-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_educationsection_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationsection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
