# Generated by Django 5.0.7 on 2024-09-10 20:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_educationsection_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationsection',
            old_name='extra',
            new_name='extra1',
        ),
        migrations.AddField(
            model_name='educationsection',
            name='extra2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
