# Generated by Django 5.0.7 on 2024-09-10 21:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_experiencesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='personal_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='personal_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='personal_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='personal_images/')),
                ('extra', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
